name: Build

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: NPM Build
              run: |
                npm ci
                npm run build
            - name: ESLint checks
              uses: gimenete/eslint-action@1.0
            - name: NPM Test
                run: |
                    npm run lint
                    npm run test
