name: Build

on: [push]

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@master
            -   name: Use Node.js
                uses: actions/setup-node@master
            -   name: Install dependencies
                run: npm ci
            -   name: Save dependencies
                    uses: actions/upload-artifact@v1
                    with:
                        name: node_modules
                        path: node_modules
    test:
        needs: install
        runs-on: ubuntu-latest
        steps:
            -   name: Use Node.js
                uses: actions/setup-node@master
            -   name: Load dependencies
                    uses: actions/download-artifact@v1
                    with:
                        name: node_modules
            -   name: NPM Test
                run: |
                    npm run lint
                    npm run test
